### ISSUE TITLE
Why option`bindProp` doesn’t be mentioned in document?

### ISSUE THREAD

**Issue by zzuieliyaoli** [backToNature/touchFeedback#1]
Thanks for your brilliant code.

When I read source code, I found `option.bindType` is custom.
However the document  doesn't refer to this.
So...

**Comment by backToNature** [comment]
Thanks , you are observant.

I think API should be as simple as possible, too many options will make people confused. 

Compared to `attribute`,the risk of `className conflict` is  more likely , so I just write the `option.feedbackClass` in document.

**Comment by zzuieliyaoli** [comment]
@backToNature Ok, I got it.
