### ISSUE TITLE
这里所谓的"没有延迟"是什么意思?

### ISSUE THREAD

**Issue by cocody** [backToNature/touchFeedback#2]
只是视觉上的"没有延迟",还是实现了fastclick一样的click事件"没有延迟"?

**Comment by backToNature** [comment]
用``:active``伪类或者``<a></a>``标签的话在安卓手机上会有明显的延迟，可以在[测试链接](http://www.dearhaoge.com/touchFeedback/demo/delay-test.html)上测一测。

从原理上来讲，就是因为这两种方案在很多浏览器都是以``click``作为触发条件的，所以会有延迟。而这个组件使用另外一种方案，是没有延迟的。

**Comment by cocody** [comment]
用了 touchstart 会有点击穿透

**Comment by backToNature** [comment]
贴一下源码看看

**Comment by cocody** [comment]
哦,测试了下,不能当做 `fastclick`来使用,如果只绑定 `touchstart ` 就会穿透

**Comment by backToNature** [comment]
可能你理解有误，这个组件并不是用来解决穿透问题的。
