### ISSUE TITLE
同时触发touchstart的元素touchend后其中一个的feebback类没有被清除

### ISSUE THREAD

**Issue by Sevody** [backToNature/touchFeedback#4]
父元素设置了feedback的平级的两个div

``` html
<div className="wraper">
    <div class="select-option" data-touchFeedback="true">姑获鸟</div>
    <div class="select-option" data-touchFeedback="true">青行灯</div>
</div>
```

同时点击两个div元素, 先后触发touchstart, eventData中的target被赋值为后触发那个dom节点, 于是之后两者先后触发的touchend事件的target皆为同一个, 导致先触发touchstart的dom节点没有执行removeClass方法

**Comment by backToNature** [comment]
感谢反馈，可以理解为这个[case](http://www.dearhaoge.com/touchFeedback/demo/sibling.html)一样吗?

如果不是的话，请提供一下完整的代码。

**Comment by Sevody** [comment]
对, 就是这种[情况](http://www.dearhaoge.com/touchFeedback/demo/sibling.html)

**Comment by backToNature** [comment]
我这边没有看出有什么问题，需要怎么复现这个问题？

**Comment by Sevody** [comment]
在手机上用两根手指同时点击A, B两个botton并马上放开, 会出现其中一个button仍处在被点击状态的情况

**Comment by backToNature** [comment]
感谢反馈，已经支持`多点触控`，[case](http://www.dearhaoge.com/touchFeedback/demo/sibling.html)上可以看到。
